-- Western Avenue order database
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  customer_name text not null,
  phone text not null,
  address text not null,
  city text not null,
  pin_code text not null,
  items jsonb not null,
  total numeric(12,2) not null,
  payment_method text not null default 'card',
  status text not null default 'new'
);

alter table public.orders enable row level security;

-- Customer site can create orders, but cannot read/update/delete them.
drop policy if exists "public can create orders" on public.orders;
create policy "public can create orders" on public.orders
for insert to anon, authenticated
with check (status = 'new');

-- Admin reads/updates orders only when signed in.
drop policy if exists "signed in admins can read orders" on public.orders;
create policy "signed in admins can read orders" on public.orders
for select to authenticated
using ((auth.jwt() ->> 'email') = 'YOUR_ADMIN_EMAIL');

drop policy if exists "signed in admins can update orders" on public.orders;
create policy "signed in admins can update orders" on public.orders
for update to authenticated
using ((auth.jwt() ->> 'email') = 'YOUR_ADMIN_EMAIL')
with check ((auth.jwt() ->> 'email') = 'YOUR_ADMIN_EMAIL');

-- Optional profile table for customer names from Supabase Auth.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  created_at timestamptz not null default now()
);
alter table public.profiles enable row level security;

drop policy if exists "users can read own profile" on public.profiles;
create policy "users can read own profile" on public.profiles
for select to authenticated using (auth.uid() = id);

drop policy if exists "users can insert own profile" on public.profiles;
create policy "users can insert own profile" on public.profiles
for insert to authenticated with check (auth.uid() = id);
